### ISSUE TITLE
Call to alias "AddSiteApplication" completes but no application visible in IIS.

### ISSUE THREAD

**Issue by sunilshahi** [SharpeRAD/Cake.IIS#52] opened 2018-07-09 05:48 UTC
This is my task. 

![image](https://user-images.githubusercontent.com/14316938/42432294-78b9bdfc-830f-11e8-8cb6-ef7ad2c72f6b.png)

When I run `.\build.ps1 --target=create-application`

I see no error.

![image](https://user-images.githubusercontent.com/14316938/42432325-97f09c22-830f-11e8-9586-276e35532e94.png)

When I look in IIS there is no application created there. Refresh did not help.

![image](https://user-images.githubusercontent.com/14316938/42432274-64f0a68c-830f-11e8-817e-19b850b12ab2.png)

If I re-run I get error saying application already exists.

![image](https://user-images.githubusercontent.com/14316938/42432430-1b376264-8310-11e8-8904-0ba1ac4450af.png)

Running appcmd list reveals that its indeed there.
![image](https://user-images.githubusercontent.com/14316938/42432356-cd1d3ee6-830f-11e8-8dde-b766571c60a1.png)

What am I missing? I can run appcmd and create the application.
 `appcmd add app /site.name:"Default Web Site" /path:/myapp /physicalPath:"C:\inetpub\myapp"`

![image](https://user-images.githubusercontent.com/14316938/42432642-1db6f3dc-8311-11e8-8bd3-7e476b0bf12d.png)

![image](https://user-images.githubusercontent.com/14316938/42432654-2f599266-8311-11e8-9fd8-fec292a44769.png)

However "AddSiteApplication" alias is not working for me. Am I missing anything?

**Comment by SharpeRAD** [comment] 2018-08-12 14:03
Sorry but it looks like your issue is that the IIS-Manager UI did not refresh, rather than the application wasn't created by Cake.IIS which is out of scope for this project.

**Closed by SharpeRAD** 2018-08-12 14:03 UTC

**Comment by Azkel** [comment] 2018-10-18 07:05
@SharpeRAD , I have the same issue.

```
Task("Create-
.Description("Adds Test Application to Test Website")
.Does(() => 
{
    AddSiteApplication(new ApplicationSettings()
    {
        SiteName = "Test",
        ApplicationPool = "Test",
        ApplicationPath = "/Test2",
	VirtualDirectory = "/Test2",
        PhysicalDirectory  = @"C:\Temp"
    });
});
```
End-result of running Cake: 
![image](https://user-images.githubusercontent.com/6032755/47136436-f834f800-d2b3-11e8-83ea-3b1d828f2f7a.png)

While on the left-side context menu Application is not visible, if I click "View Applications" on Right-side menu after selecting "Test" Site, I see it on the list, but without Physical Path filled. After filling Physical path with i.e. `C:\Temp` everything works as intended, and I can see this Application as a child of "Test" site. `C:\Temp` is a proper, existing path in my system. I'm using IIS 10.0.17134.1.

I'll look into it, and if I find any fix I'll propose PR with fix.
